server:
  port: 8888
spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/krishna8git/microservices-spring-cloud.git
          searchPaths: config-server/config-repo/licensingservice
          timeout: 4
